blank_issues_enabled: true
contact_links:
  - name: Feature Request
    url: https://github.com/CraftTrident/Trident/discussions/new?category=feature-requests
    about: Suggest an idea for Trident
  - name: Exploit Report
    url: https://www.github.com/CraftTrident
    about: |
      Since GitHub does not allow private issues, exploit reports are currently handled through our Discord.
      To report an exploit, contact a moderator on the Trident Discord.
  - name: Discord (COMING SOON)
    url: https://github.com/CraftTrident
    about: If you are having issues with Spark profiling or have other minor issues, come join our Discord server for help!